version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.example
    container_name: hello-bff
    restart: always
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./storage
        target: /storage
    environment:
      STORAGE_PATH: /storage
      ALLOWED_FILE_EXTENSIONS: "jpg,jpeg,png,gif,svg,txt,pdf,xlsx"
      PORT: 3000