name: Continuous Deleviry - Workflow
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install packages
        run: npm install

      - name: Unit tests
        run: npm run test

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Add Release Tag
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: 'v'
          bump_version_scheme: 'minor'

      - name: Check Output Parameters
        run: |
          echo "Get repository name ${{ github.event.repository.name }}"
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        if: contains(github.ref, 'refs/tags/v')
        with:
          context: .
          push: true
          tags: heliandro/${{ github.event.repository.name }}:${{ steps.release.outputs.tag_name }}